export const items=[
    {
        id: 1,
        title:`Women's Tosca City Run`,
        catogery:"women",
        gender:"female",
        details:"Auctor eros suspendisse tellus venenatis sodales purus non pellentesque amet, nunc sit eu, enim fringilla egestas pulvinar odio feugiat consectetur egestas magna pharetra cursus risus, lectus enim eget eu et lobortis faucibus.",
        image:require("../Assets/image/shoes/1.jpg"),
        qty:1,
        price:1200,
    },
    {
        id: 11,
        title:`Men's Earth-Tone Sneaker`,
        catogery:"men",
        gender:"male",
        details:"Auctor eros suspendisse tellus venenatis sodales purus non pellentesque amet, nunc sit eu, enim fringilla egestas pulvinar odio feugiat consectetur egestas magna pharetra cursus risus, lectus enim eget eu et lobortis faucibus.",
        image:require("../Assets/image/shoes/11.jpg"),
        qty:1,
        price:1200,
    },
    {
        id: 2,
        title:`Women's Pink Training`,
        catogery:"women",
        gender:"female",
        details:"Auctor eros suspendisse tellus venenatis sodales purus non pellentesque amet, nunc sit eu, enim fringilla egestas pulvinar odio feugiat consectetur egestas magna pharetra cursus risus, lectus enim eget eu et lobortis faucibus.",
        image:require("../Assets/image/shoes/2.jpg"),
        qty:1,
        price:1200,
    },
    {
        id: 3,
        title:`Women's Pink Suede`,
        catogery:"women",
        gender:"female",
        details:"Auctor eros suspendisse tellus venenatis sodales purus non pellentesque amet, nunc sit eu, enim fringilla egestas pulvinar odio feugiat consectetur egestas magna pharetra cursus risus, lectus enim eget eu et lobortis faucibus.",
        image:require("../Assets/image/shoes/3.jpg"),
        qty:1,
        price:1200,
    },
    {
        id: 4,
        title:`Women's Orange Sneaker`,
        catogery:"women",
        gender:"female",
        details:"Auctor eros suspendisse tellus venenatis sodales purus non pellentesque amet, nunc sit eu, enim fringilla egestas pulvinar odio feugiat consectetur egestas magna pharetra cursus risus, lectus enim eget eu et lobortis faucibus.",
        image:require("../Assets/image/shoes/4.jpg"),
        qty:1,
        price:1200,
    },
    {
        id: 14,
        title:`Men's Navy Running`,
        catogery:"men",
        gender:"male",
        details:"Auctor eros suspendisse tellus venenatis sodales purus non pellentesque amet, nunc sit eu, enim fringilla egestas pulvinar odio feugiat consectetur egestas magna pharetra cursus risus, lectus enim eget eu et lobortis faucibus.",
        image:require("../Assets/image/shoes/14.jpg"),
        qty:1,
        price:1200,
    },
    {
        id: 5,
        title:`Women's Mint Sneaker`,
        catogery:"women",
        gender:"female",
        details:"Auctor eros suspendisse tellus venenatis sodales purus non pellentesque amet, nunc sit eu, enim fringilla egestas pulvinar odio feugiat consectetur egestas magna pharetra cursus risus, lectus enim eget eu et lobortis faucibus.",
        image:require("../Assets/image/shoes/5.jpg"),
        qty:1,
        price:1200,
    },
    {
        id: 13,
        title:`Men's Classic Blue`,
        catogery:"men",
        gender:"male",
        details:"Auctor eros suspendisse tellus venenatis sodales purus non pellentesque amet, nunc sit eu, enim fringilla egestas pulvinar odio feugiat consectetur egestas magna pharetra cursus risus, lectus enim eget eu et lobortis faucibus.",
        image:require("../Assets/image/shoes/13.jpg"),
        qty:1,
        price:1200,
    },
    {
        id: 6,
        title:`Women's Green Training`,
        catogery:"women",
        gender:"female",
        details:"Auctor eros suspendisse tellus venenatis sodales purus non pellentesque amet, nunc sit eu, enim fringilla egestas pulvinar odio feugiat consectetur egestas magna pharetra cursus risus, lectus enim eget eu et lobortis faucibus.",
        image:require("../Assets/image/shoes/6.jpg"),
        qty:1,
        price:1200,
    },
    {
        id: 12,
        title:`Men's Black Running`,
        catogery:"men",
        gender:"male",
        details:"Auctor eros suspendisse tellus venenatis sodales purus non pellentesque amet, nunc sit eu, enim fringilla egestas pulvinar odio feugiat consectetur egestas magna pharetra cursus risus, lectus enim eget eu et lobortis faucibus.",
        image:require("../Assets/image/shoes/12.jpg"),
        qty:1,
        price:1200,
    },
    {
        id: 7,
        title:`Women's Cream Suede`,
        catogery:"women",
        gender:"female",
        details:"Auctor eros suspendisse tellus venenatis sodales purus non pellentesque amet, nunc sit eu, enim fringilla egestas pulvinar odio feugiat consectetur egestas magna pharetra cursus risus, lectus enim eget eu et lobortis faucibus.",
        image:require("../Assets/image/shoes/7.jpg"),
        qty:1,
        price:1200,
    },
    {
        id: 8,
        title:`Women's Choco City Run`,
        catogery:"women",
        gender:"female",
        details:"Auctor eros suspendisse tellus venenatis sodales purus non pellentesque amet, nunc sit eu, enim fringilla egestas pulvinar odio feugiat consectetur egestas magna pharetra cursus risus, lectus enim eget eu et lobortis faucibus.",
        image:require("../Assets/image/shoes/8.jpg"),
        qty:1,
        price:1200,
    },
    {
        id: 9,
        title:`Men's Green Running`,
        catogery:"men",
        gender:"male",
        details:"Auctor eros suspendisse tellus venenatis sodales purus non pellentesque amet, nunc sit eu, enim fringilla egestas pulvinar odio feugiat consectetur egestas magna pharetra cursus risus, lectus enim eget eu et lobortis faucibus.",
        image:require("../Assets/image/shoes/9.jpg"),
        qty:1,
        price:1200,
    }, 
    {
        id: 10,
        title:`Men's Moonstone Sneaker`,
        catogery:"men",
        gender:"male",
        details:"Auctor eros suspendisse tellus venenatis sodales purus non pellentesque amet, nunc sit eu, enim fringilla egestas pulvinar odio feugiat consectetur egestas magna pharetra cursus risus, lectus enim eget eu et lobortis faucibus.",
        image:require("../Assets/image/shoes/10.jpg"),
        qty:1,
        price:1200,
    },
   
   
  
   
]